### ISSUE TITLE
Check if there's a way for the linter to impose the "grouping import" convention

### ISSUE THREAD

**Issue by tgragnato** [tgragnato/magnetico#13]
According to this convention, imports are typically grouped into three sections, and each section is separated by a blank line:

1. Standard library imports
2. Third-party package imports
3. Your own package imports

Ref: https://github.com/tgragnato/magnetico/pull/12/commits/3d346ad3949fea9d300fcd14a91c189f9f00e122

**Comment by capricornusx** [comment]
I was found [gci](https://github.com/daixiang0/gci), test CI in progress...

**Comment by capricornusx** [comment]
Solution:
`gci write -s standard -s default -s "prefix(github.com/tgragnato/magnetico)" -s blank -s dot .`
