### ISSUE TITLE
Fix and enable `codecov-action`

### ISSUE THREAD

**Issue by tgragnato** [tgragnato/magnetico#14]
Experiment with actions using go-test-coverage
https://github.com/marketplace/actions/go-test-coverage

**Comment by capricornusx** [comment]
What coverage threshold will suit us?

**Comment by tgragnato** [comment]
Instead of aiming for a specific threshold, I suggest we prioritize writing meaningful tests that cover critical functionality and edge cases. This approach ensures that our testing efforts are effective and contribute to a robust codebase.

Ultimately, our goal should be to establish a testing framework that gives us the assurance to make changes confidently, knowing that our tests provide adequate protection against potential issues.

**Comment by tgragnato** [comment]
https://github.com/tgragnato/magnetico/blob/afacc2b41caff3f2eb2e9c9aedd967c19f3ab7c4/.github/workflows/go.yml#L28

**Comment by capricornusx** [comment]
> https://github.com/tgragnato/magnetico/blob/afacc2b41caff3f2eb2e9c9aedd967c19f3ab7c4/.github/workflows/go.yml#L28-L29

It seems you need to register (it's free) on the website https://about.codecov.io/

**Comment by tgragnato** [comment]
> > https://github.com/tgragnato/magnetico/blob/afacc2b41caff3f2eb2e9c9aedd967c19f3ab7c4/.github/workflows/go.yml#L28-L29
> 
> It seems you need to register (it's free) on the website https://about.codecov.io/

I have the token, but there are issues with the action I need to debug :)
I'm working on it 👍🏼
