### ISSUE TITLE
magnetico doesn't generate a node-id

### ISSUE THREAD

**Issue by Phasip** [tgragnato/magnetico#169]
Hello!

Looking at what is communicated using wireshark it seems like magnetico always uses node-id 0000...

Code seems to agree with this behaviour:
https://github.com/tgragnato/magnetico/blob/cb7243bb2d9e6a5bfe302dd54bbc51ccdd8f7d18/dht/mainline/indexingService.go#L63

Is there a reason for using the 0000 id or is this a bug?

**Comment by tgragnato** [comment]
It's a bug! (magnetico has yet to implement many features of the mainline dht protocol)
***BEP5*** says `nodeID` is a globally unique identifier chosen at random

Great catch, thanks
