### ISSUE TITLE
Legacy code?

### ISSUE THREAD

**Issue by capricornusx** [tgragnato/magnetico#17]
I think this can be removed (it seems to be legacy of code that was used for debugging)

https://github.com/tgragnato/magnetico/blob/ad0c0ebc2d106b5c4dbe16dccdd42b422178a4a6/metadata/sink.go#L79-L85

**Comment by tgragnato** [comment]
+1, the counter was used for logging purposes. https://github.com/tgragnato/magnetico/commit/1fdfa131aaeae371a1702ecd02fc8933287ce44a

I decided to remove structured logging back when I forked the project...
I believe that the target audience is not actively using this kind of logs, and that they do not provide substantial value.
