### ISSUE TITLE
Torrents stop adding after a while

### ISSUE THREAD

**Issue by Phasip** [tgragnato/magnetico#178]
After running for a while the leechers are all used up and will not allow addition of new leeches.
You can test this by adding some debug output and running with `--leech-max-n=1`.

The issue lies in the Sink which leaves zero-length peer lists in the ms.incomingInfoHashes when it handles the last peer of an infohash. This should be cleared by onError.

I.e a delete is needed here: https://github.com/tgragnato/magnetico/blob/51ae9699e6b7d810ede61f3a57f1119abff4c6a7/metadata/sink.go#L122

However, adding that breaks the current tests due to race-conditions.

**Comment by tgragnato** [comment]
Should be fixed with https://github.com/tgragnato/magnetico/commit/a98fa14fa62eedebd42a46ed9a5dc7cc287a4328.

**Comment by Phasip** [comment]
Works fine, great work! I take the liberty of closing this.
