### ISSUE TITLE
Wrong condition or golang specific behavior

### ISSUE THREAD

**Issue by capricornusx** [tgragnato/magnetico#22]
Why is the checked length equal to 1 here, if the second element is also used?

if `len(peerAddrs) = 1` then `ms.incomingInfoHashes[infoHash] = peerAddrs[1:]` will cause an error or nothing (because empty slice)?

I think the check needs to be corrected to `len(peerAddrs) < 2`

```go
if len(peerAddrs) < 1 {
    return
}
```

https://github.com/tgragnato/magnetico/blob/afacc2b41caff3f2eb2e9c9aedd967c19f3ab7c4/metadata/sink.go#L93-L106

similar behavior occurs further:
https://github.com/tgragnato/magnetico/blob/afacc2b41caff3f2eb2e9c9aedd967c19f3ab7c4/metadata/sink.go#L141-L145

**Comment by tgragnato** [comment]
In Go (Golang), peerAddrs[1:] is a slice expression. it takes a slice (peerAddrs) and creates a new slice that includes all elements starting from the second element (index 1) to the end of the original slice. The original peerAddrs slice is not modified; instead, a new slice is created.

**Comment by tgragnato** [comment]
```
package main

import (
	"fmt"
)

func main() {
	singleItem := []string{"test"}
	newSlice = singleItem[1:]
	fmt.Println(newSlice)
}
```

newSlice is an empty slice
