### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by ireun** [tgragnato/magnetico#235]
Would you mind expanding readme with instructions on running this? Especially in docker for windows.

**Comment by tgragnato** [comment]
Unfortunately, I don't have access to a Docker environment on Windows to directly test this.
Could you possibly test some general instructions on a Windows setup and share your experience?

**Comment by danieldownes** [comment]
I'm also struggling to run this and think some instructions would be helpful.

Can you add Ubuntu instructions? (Windows allows native access to most Linux distrutions anyway).

I've used Docker quite a bit, but can't seem to get this working.
When I run make there is an error online 15 too.

Even though I am a developer with 25+ years experience I am not very familier with the toolchain required to get this work.

**Comment by danieldownes** [comment]
I've been able to get this working using windows, although I did install WSL.

Powershell:
```
wsl --list
wsl install Ubuntu24
```
Create a username and password then follow the instructions I worked out in [this issue](https://github.com/tgragnato/magnetico/issues/236).

**Comment by tgragnato** [comment]
Hello,

I wanted to let you know that I have updated the README file with useful instructions. Please take a look and let me know if this helps.

Thank you!

**Comment by tgragnato** [comment]
With [this commit](https://github.com/tgragnato/magnetico/commit/3beccffe2918056360214052fddb06cf5e52b6a6), the [README](https://github.com/tgragnato/magnetico/blob/main/README.md) should provide general guidelines on how to handle data persistence in the project.
These guidelines cover best practices and recommended approaches.

Further details on how to configure the parameters for optimal crawling performance will follow.
