### ISSUE TITLE
bitmagnet.io

### ISSUE THREAD

**Issue by capricornusx** [tgragnato/magnetico#24]
I find this project - [bitmagnet.io](https://bitmagnet.io).
This seems to be a more complete solution for users. Maybe we can join them? ;)

**Comment by tgragnato** [comment]
bitmagnet itself is inspired by magnetico https://bitmagnet.io/internals-development/dht-crawler.html
Currently the two projects are not compatible, from a codebase standpoint. 
 
This fork of Magnetico aims to achieve a significant simplification of the code and is perhaps closer to support crawling IPv6. On the other hand, Bitmagnet has introduced the content classifier and the integration with the Servarr stack.
