### ISSUE TITLE
Running on Ubuntu - "Easy installation" in readme is deceptive!

### ISSUE THREAD

**Issue by danieldownes** [tgragnato/magnetico#346]
Its clear that this is not an "Easy installation" as the readme would suggest.

After 4 hours of my time, 20+ years of computing experience, added googling and prompting, here is what I've been able to do so far from a fresh install of Ubuntu (24):

```
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# DB
sudo docker pull postgres
sudo docker run --net=host --name magnetico-postgres -e POSTGRES_USER=magnetico -e POSTGRES_PASSWORD=magnetico -e POSTGRES_HOST_AUTH_METHOD=trust -d postgres
sudo docker exec -it magnetico-postgres bash
psql -U magnetico
CREATE EXTENSION pg_trgm;
quit

# magnetico
git clone https://github.com/tgragnato/magnetico
cd ./magnetico
docker build -t mag .
sudo docker run --net=host --rm -it --name contmag --entrypoint "/bin/sh" prjmag -c /usr/bin/magneticod
```

Then to get the web server, magneticow, running, start another terminal and then:
```
sudo docker exec -it contmag /usr/bin/magneticow --no-auth
```

I am super happy to report that this seems to be working after a lot of messing around.

However, as from the origonal repo, and related press coverage, I would have expected it to be easier to run?!

Can this be simplifed at all? In the origonal repo they simple state the you can run `make docker` that it sets everything up and runs both serives, however it never worked for me.

**Comment by tgragnato** [comment]
Closed in favor of https://github.com/tgragnato/magnetico/issues/235
Perhaps we could document the need for pg_trgm there.
