### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by Glandos** [tgragnato/magnetico#42]
Hi, and many thanks for taking care of magnetico!

I'm a long time user of it (since the python version in fact), and still using an SQLite database, because I found that performance and storage space of PostgreSQL doesn't fit my need.

I saw that you removed SQLite in 5ed7d99cd6af11d4058680c8a2acbcbeb67062a5

Do you plan to support it, at least for scraping the DHT? I guess that you removed it because it didn't fit your needs for the web interface, but… it's just a guess :)

**Comment by tgragnato** [comment]
Hi there,

Thank you for reaching out! I had concerns about the performances of SQLite, but I would have gladly maintained the existing support.

Unfortunately `anacrolix/torrent` at a certain point introduced some SQLite libraries, after that change the CGO linker started breaking due to duplicated symbols. (`duplicate symbol _sqlite3_*` / `multiple definition of sqlite3_*`)

Ref: https://github.com/golang/go/pull/61529

I decided to update the library and remove the support for SQLite. It was supposed to be temporary measure, but the issue is still not fixed 🙃

**Comment by Glandos** [comment]
I have a 85GB SQLite database with 25.3M torrents. So far, `magneticow` answers in less than 2 seconds, on my Intel(R) Atom(TM) CPU D2550. The only modern part is the SSD Samsung 850 Pro, so I/O are fast.

Of course, `magneticow` uses "simple" requests, I don't know if adding multiple columns won't change the game.

**Comment by Phasip** [comment]
Hello!

What is the state of this issue right now? Everything seems to build and the code seems to contain sqlite support. But when running I get the following errors:

```
/magneticod --database=sqlite3:$(pwd)/sqlite3.db
...
2024/03/15 15:51:26 Could not add new torrent to the database. tx.Exec (INSERT OR REPLACE INTO torrents) database disk image is malformed
```

 ```
/magneticod --database=sqlite3:memory
...
2024/03/15 15:53:05 Could not add new torrent to the database. no such table: torrents
```

**Comment by tgragnato** [comment]
Hi @Phasip,

I switched to a local module for `anacrolix/torrent` by using a replace statement in go.mod and removed the SQLite dependency from there as a ***workaround*** for Go's bug.

I suspect there is a ***regression*** in either the SQLite driver or SQLite itself. As you can see, whenever magneticod tries to insert a new torrent with an up-to-date version of SQLite, the database disk image ends up being malformed.

Another issue with sqlite is that each connection to `:memory:` opens a brand new in-memory sql database, when the stdlib's sql engine opens another connection we will see a brand new database. A workaround is to use `:memory:?cache=shared`, with a DSN of this kind every connection will point to the same in-memory database.

To ensure a functioning SQLite persistence backend, ***I reverted to the old driver version***.
It should be working, but any assistance or feedback in this regard is greatly appreciated!

**Comment by Phasip** [comment]
The sqlite3 seems to work for me now

**Comment by rnhmjoj** [comment]
> What is the state of this issue right now? Everything seems to build and the code seems to contain sqlite support. But when running I get the following errors:
> 2024/03/15 15:51:26 Could not add new torrent to the database. tx.Exec (INSERT OR REPLACE INTO torrents) database disk image is malformed

You get the same error even with the original magnetico after you bump some Go dependencies. 
The problem of the duplicated symbols can be worked around using an external sqlite (`-tags libsqlite3`), but you still get that error, so it really looks like a bug in the driver or sqlite.
