### ISSUE TITLE
Loading and displaying NFO

### ISSUE THREAD

**Issue by 5zzd** [tgragnato/magnetico#472]
This is probably the only way to add your own descriptions to static WEB pages of the magnetico site.

This commit makes me sad: [commit/a1884eb8c15dcbf83c213164e107e122bdad8509](https://github.com/tgragnato/magnetico/commit/a1884eb8c15dcbf83c213164e107e122bdad8509)
Should we expect this functionality to return?

Thanks!

**Comment by tgragnato** [comment]
> Should we expect this functionality to return?

Maybe!

Initially, I forked Magnetico to update it and make it conform to my personal taste and needs. I might be wrong, but I still consider this repository from this perspective.

I deeply hated having to interact with anacrolix’s torrent implementation. If I develop something in my free time, it has to be for pleasure. With [this change](https://github.com/tgragnato/magnetico/pull/470), I finally managed to get rid of most of that code.

A torrent client is obviously a necessary prerequisite for downloading NFO files. You might see this feature return when someone contributes an integration with an alternative torrent client.

**Comment by 5zzd** [comment]
> I deeply hated having to interact with anacrolix’s torrent implementation. If I develop something in my free time, it has to be for pleasure. With [this change](https://github.com/tgragnato/magnetico/pull/470), I finally managed to get rid of most of that code.

I accept you.

> A torrent client is obviously a necessary prerequisite for downloading NFO files. You might see this feature return when someone contributes an integration with an alternative torrent client.

Thanks!
