### ISSUE TITLE
Understanding a possible memory leak

### ISSUE THREAD

**Issue by Fabricio20** [tgragnato/magnetico#476]
| Q                   | A      |
| ------------------- | ------ |
| BC Break            | no|
| Version             | https://github.com/tgragnato/magnetico/commit/13396242fb1972a928b11d44c792bac659d26ac7  |

### Support Question

I've been analyzing the memory leak I mentioned on https://github.com/tgragnato/magnetico/pull/474#issuecomment-2316205526 and right now I have more questions than answers.

During a ~12h period since that comment magnetico crashed about once per hour for having ran out of memory, more specifically systemd-oomd killed the process as all ram+swap (8G + 4G) was full. There is nothing else running on the machine, only magneticod under systemd.

```
Aug 29 13:59:44 dht kernel: Out of memory: Killed process 5757 (magnetico) total-vm:17558160kB, anon-rss:7180560kB, file-rss:5528kB, shmem-rss:0kB, UID:0 pgtables:28264kB oom_score_adj :0
Aug 29 13:59:44 dht systemd[1]: magnetico.service: A process of this unit has been killed by the OOM killer.
Aug 29 13:59:46 dht systemd[1]: magnetico.service: Main process exited, code=killed, status=9/KILL
Aug 29 13:59:46 dht systemd[1]: magnetico.service: Failed with result 'oom-kill'.
Aug 29 13:59:46 dht systemd[1]: magnetico.service: Consumed 1h 337ms CPU time, 7.3G memory peak, 3.7G memory swap peak.
Aug 29 13:59:46 dht systemd[1]: magnetico.service: Scheduled restart job, restart counter is at 1.
```

I looked into how heap dumps work on golang and managed to take a few dumps using pproc, I also noticed you pushed a [commit](https://github.com/tgragnato/magnetico/commit/13396242fb1972a928b11d44c792bac659d26ac7) that looks like a workaround for the "issue" described on https://github.com/tgragnato/magnetico/issues/464. 

There you mentioned that the huge allocations from the node list made by `addNode` would not be an issue if the processing thread was faster, however under normal conditions it was advisable to rate limit how fast the crawler goes with the `--max-rps` parameter.

Looking at some of these dumps, it looked like the `addNode` function (even with your patch from https://github.com/tgragnato/magnetico/commit/13396242fb1972a928b11d44c792bac659d26ac7) was still the biggest allocator, as you can see on some of the earlier dumps below, however you can see that actually your commit logic doesn't seem to be running at all:

![image](https://github.com/user-attachments/assets/af579a07-b464-448b-ac58-2152a556c52a)

If my understanding of this profiler is correct, this means that the `nodes` array still had less entries than `rt.maxNeighbors*rt.maxNeighbors` and as I was running the default config, that value was at `10_000 * 10_000 = 100_000_000`. 

I then decided to re-setup magnetico with `--indexer-max-neighbors=1000` so this value would be much lower, having done that, the torrent output rate fell by half (from ~3 torrents/s to 1/s or so) as did the network usage, however after one entire hour running (remember, magnetico was crashing about once per hour) I had not seen a crash and systemd reported that the peak memory usage was only `385.7M`. 

This makes no sense, how come before we were having peaks of 8GB and then GC would run and clean stuff up, and now having reduced the array size to 10% of the original we were only using a tiny fraction of the memory over the same period of time? It also doesn't really match what the heap dump says at all (4gb vs 8gb, is the extra 4gb "off-heap" as I would call it in the Java world)? At this point I took another heap dump and well:

![image](https://github.com/user-attachments/assets/06f0c7ee-f1a1-42f5-9f42-cf725982c679)

It still looks like the failsafe code isn't even running, which still means we are well below the (now `1_000_000`) entries limit. I then realised that "wait a minute", the `4.5GB` usage by the `addNode` function (from the other dump) did not match at all the actual heap usage by the golang binary, as systemd was reporting near ~11gb (almost crashing) when I took that dump.

```
magnetico.service - magneticod
     Loaded: loaded (/etc/systemd/system/magnetico.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-08-29 12:53:52 UTC; 1h 1min ago
 Invocation: 85733d42ee6c4d0f9746a6d9dc8f8fd7
   Main PID: 5757 (magnetico)
      Tasks: 13 (limit: 9488)
     Memory: 5.6G (peak: 7.3G swap: 55.1M swap peak: 3.4G)
        CPU: 55min 44.892s
     CGroup: /system.slice/magnetico.service
             └─5757 /usr/bin/magnetico --daemon --indexer-addr=<ip>:<port> --database=zmq://0.0.0.0:2222
```

I left the `--indexer-max-neighbors=1000` one running for an extra hour and it crashed with a peak of `385.7M` due to what looks like an issue with the [ZMQ connector](https://github.com/tgragnato/magnetico/blob/main/persistence/zeromq.go#L54). It's now running again under the same limit and I will report back in case I see another oom crash.

```
Aug 29 16:19:05 dht magnetico[6966]: 2024/08/29 16:19:05 Could not add new torrent to the database. Failed to transmit send frame error
Aug 29 16:19:05 dht systemd[1]: magnetico.service: Main process exited, code=exited, status=1/FAILURE
Aug 29 16:19:05 dht systemd[1]: magnetico.service: Failed with result 'exit-code'.
Aug 29 16:19:05 dht systemd[1]: magnetico.service: Consumed 47min 58.038s CPU time, 385.7M memory peak.
Aug 29 16:19:05 dht systemd[1]: magnetico.service: Scheduled restart job, restart counter is at 2.
Aug 29 16:19:05 dht systemd[1]: Started magneticod.
```

I'm pretty lost right now as to what is causing all the oom crashes, and from monitoring over `htop` it looks very bursty, suddenly magnetico starts allocating several gigabytes of memory in a span of less than 5 seconds only to release (almost) it all back over the next 2-3 minutes. Maybe i've been encountering some rogue/malicious giant torrent file that has a several gigabytes metadata section?

Any tips in how to better diagnose this issue are welcome (such as ways to get better heap dumps, and other things to look out for), I feel like i've exhausted what golang knowledge I have at this point!

| heap | version | notes |
|------|--------|--------|
| [heap_1.zip](https://github.com/user-attachments/files/16803042/heap_1.zip) | https://github.com/tgragnato/magnetico/commit/13396242fb1972a928b11d44c792bac659d26ac7 | initial heap dump |
| [heap_2.zip](https://github.com/user-attachments/files/16803044/heap_2.zip) | https://github.com/tgragnato/magnetico/commit/13396242fb1972a928b11d44c792bac659d26ac7 | half hour dump |
| [heap_3.zip](https://github.com/user-attachments/files/16803046/heap_3.zip) | https://github.com/tgragnato/magnetico/commit/13396242fb1972a928b11d44c792bac659d26ac7 | right before crash ~7.3gb on systemd |
| [heap_4.zip](https://github.com/user-attachments/files/16803057/heap_4.zip) | https://github.com/tgragnato/magnetico/commit/13396242fb1972a928b11d44c792bac659d26ac7 | after one hour under `--indexer-max-neighbors=1000` |

**Comment by tgragnato** [comment]
> Maybe i've been encountering some rogue/malicious giant torrent file that has a several gigabytes metadata section?

Yes, in the past, there have been reports of torrents with abnormally large metadata files, which could indeed contain malicious code or simply be poorly designed, causing issues and oom kills.

However, the leecher includes [this size check](https://github.com/tgragnato/magnetico/blob/ba08b842bcb0d037f954b89198afd2265620567e/metadata/leech.go#L156) to avoid [downloading or handling](https://github.com/tgragnato/magnetico/blob/ba08b842bcb0d037f954b89198afd2265620567e/metadata/leech.go#L160) torrents with corrupted or excessively large metadata.

>  is the extra 4gb "off-heap" as I would call it in the Java world?

The strange behaviour you are experiencing might be indeed related to an excessive frequency with which the `rt.nodes` slice is created, modified, or resized, especially if these operations involve the allocation of new memory.

If a slice is continuously resized (for example, with append operations), and if its capacity increases significantly compared to the actual data needed, a problem may arise.

My guess is that somehow in some cases the GC isn’t fast enough, leading to OOMs and off-heap usage.
I really need to optimize the code to avoid excessive allocations.

**Comment by Fabricio20** [comment]
One more update here, it's now been running for 21h straight without crashing with the limited nodes option.

```
● magnetico.service - magneticod
     Loaded: loaded (/etc/systemd/system/magnetico.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-08-29 16:19:05 UTC; 21h ago
 Invocation: fc1aabda98b3458bbcc789cc41bce0a6
   Main PID: 7283 (magnetico)
      Tasks: 13 (limit: 9488)
     Memory: 221M (peak: 412M)
        CPU: 7h 42min 51.565s
     CGroup: /system.slice/magnetico.service
             └─7283 /usr/bin/magnetico --daemon --indexer-max-neighbors=1000 --indexer-addr=<ip>:<port> --database=zmq://0.0.0.0:2222
```

Memory peak at double the usage however still extremely low (400MB), I think this might be `rt.nodes` after all. I dont exactly know how golang handles array resizing or slicing, but it feels like it needs to copy the entire array over to do it,

That would mean, that at a 4GB memory array, adding a new entry requires recreating the array, so golang copies the entire 4GB over to new memory space (totalling 8gb) with space for the new entry, then discards the old array, gc then runs and frees up the old 4GB. At some point with more and more nodes being added, this copy operation will be enough to trigger memory exhaustion on the system.

Is there perhaps a better data structure in golang for this? Or some other way to resize the array in a way that doesn't involve copying the array, maybe a linked list? I'll try swapping this to a linked list and see how it goes.

**Comment by tgragnato** [comment]
> Or some other way to resize the array in a way that doesn't involve copying the array

This is way I'm trying to achieve in [3ced3c66d4a8c5392c23982614f9120ed3f7de51](https://github.com/tgragnato/magnetico/commit/3ced3c66d4a8c5392c23982614f9120ed3f7de51).

The aim of the change is to allocate a slice with the maximum size right from the start, and append elements carefully to avoid exceeding the already allocated size. During deletion, instead of assigning a new empty slice, the slice is replaced with 0 items from itself.

Could you please review this code? I understand that you’re not a Go developer, but your insights and heap dumps have been extremely helpful. (I had never been able to reproduce this issue before)

With **_100.000.000 nodes_**, the RAM usage is between **_9-10GB_**. I’m wondering if people are generally running magnetico on less powerful machines and whether it might be better to lower the default value for `indexer-max-neighbors`.

**Comment by Fabricio20** [comment]
I'm back with some more data, I've ran magnetico for quite a lot of hours with both your patch and my own linked list implementation. **I'll start off by saying that both seem to have resolved the issue entirely.**

My approach with the linked list was to simply drop new entries as they came in that exceeded the list size, using a linked list to prevent array copying stopped the big memory allocations and resulted instead in a linear allocation until `rt.nodes` reached its maximum allowed size. However there are a lot of downsides to this approach, one in particular is the extreme overhead that linked lists seems to add compared to your solution, as well as the entries getting "stale" after just a few minutes.

I looked at **your implementation** and as far as I can tell, once the list is filled you just discard the entire list so we never go over the limit. Ignoring some considerations i'll write below, that seems to be an approach that works, and is extremely efficient. I have a slight modification running where I removed the `maxNeighbors*maxNeighbors` multiplication just for control reasons but overall it **has been pretty stable and uses considerably less memory than the linked lists implementation** I did.

More precisely, running with `10_000_000` total entries in the list, magnetico seems to consume about 1.1gb with this patch as you can see below, it also seems to take about 2 minutes to reach this limit on the server i'm using for these tests.

```
● magnetico.service - magneticod
     Loaded: loaded (/etc/systemd/system/magnetico.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-08-30 17:29:51 UTC; 1 day 3h ago
 Invocation: 5eebe8b7081a47e3a9d270f71331e897
   Main PID: 19206 (magnetico)
      Tasks: 14 (limit: 9488)
     Memory: 1.3G (peak: 1.7G)
        CPU: 1d 15h 1min 12.730s
```
```
Aug 30 17:33:15 dht magnetico[19206]: 2024/08/30 17:33:15 routingTable nodes are full.. crawling too fast? (try to set max-rps lower)
Aug 30 17:35:08 dht magnetico[19206]: 2024/08/30 17:35:08 routingTable nodes are full.. crawling too fast? (try to set max-rps lower)
Aug 30 17:36:51 dht magnetico[19206]: 2024/08/30 17:36:51 routingTable nodes are full.. crawling too fast? (try to set max-rps lower)
Aug 30 17:38:38 dht magnetico[19206]: 2024/08/30 17:38:37 routingTable nodes are full.. crawling too fast? (try to set max-rps lower)
Aug 30 17:41:09 dht magnetico[19206]: 2024/08/30 17:41:09 routingTable nodes are full.. crawling too fast? (try to set max-rps lower)
Aug 30 17:43:34 dht magnetico[19206]: 2024/08/30 17:43:34 routingTable nodes are full.. crawling too fast? (try to set max-rps lower)
Aug 30 17:44:44 dht magnetico[19206]: 2024/08/30 17:44:44 routingTable nodes are full.. crawling too fast? (try to set max-rps lower)
```

While it shows a peak of 1.7gb in general it is extremely stable at 1.1gb, my guess is that peak was related to something else and seems to have happened during the past few hours as well. That puts us at about `110` bytes per entry in the list or so, which works as a good guesstimate for gauging how big the list should be for a given hardware configuration.

I think my main concern with this approach is the zeroing. The main goal of the tool is to scan the entire DHT and index as much as possible, by zeroing this list we may be throwing away nodes that have not yet been queried for all their hashes (or at least by a fraction of them via the `sample_infohashes` call).

I'm not entirely sure if there could be a better approach that is not much more complex. I know this list is only used on `indexingService` where it's iterated over and for every entry a `sample_infohashes` rpc call is used. How often is this sampling done by magnetico? Could we be discarding entries by zeroing this list before that indexing request was ran?

Lots of deliberation and rambling below, enjoy at your own risk! You can also close this issue as completed, your fix works and as of right now, besides maybe lowering the default on `maxNeighbors` to about `6_000` or so, as that would limit memory usage to about `4gb` by default instead of the current ~10gb. The issue has not presented itself in over 24h.

-------------------

Based off of my interpretation of [BEP51](https://www.bittorrent.org/beps/bep_0051.html), for every single node, we can call `sample_infohashes` multiple times to obtain their entire hash table, respecting each peer's rate limits of course (which we are not doing at the moment it seems?), this means that for _some_ nodes in the dht we could be losing a lot of possible hashes by discarding them from this list.

If you are up to some relatively small design changes, I think a better approach would be to remove this list entirely, or at least replace it with a queue:

- Our crawler starts by sending out `find_node` requests to our bootstrap nodes, this creates a big list of nodes for us and can continually run in the background. *Note 1 below
- For every node that replies to our `find_node`, we put them in a queue `rt.nodes`.
- Another routine can pull/remove from this queue and send a `sample_infohashes` to this entry. *Note 2 below
- If a `sample_infohashes` response arrives which has `num` > `len(samples)` we can requeue the same node. *Note 3 below
- According to BEP51, this rpc call also returns the same output that `find_nodes` would, under the `nodes`/`nodes6` keys, so we can just add those to our `rt.nodes` queue as well.
- This should allow us to transverse the entire dht network as fast as we can send out requests.

There are a few interesting challenges with this approach of course:

Note 1: Some time after bootstrapping, as more and more peers reply to our `sample_infohashes` requests we may no longer need to run `find_node` queries, as the rate of replies should be enough to keep our queue reasonably full. We could stop this routine entirely or dynamically rate limit / slow it down based off of how full `rt.nodes` is (`len(rt.nodes) < maxNeighbors`).

Note 2: The queue is mainly here to allow us to rate limit how fast we are sending out infohash requests (`max_rps` would be used to limit how fast we are pulling from this queue), but could be removed entirely and just changed to simply sending data off of as soon as the responses arrive to other queries such as `find_node` or `sample_infohashes`. I'd be concerned with UDP exhaustion/dropped packets without the queue however.

Note 3: Readding these nodes is a good approach to ensure we exhaust their infohash keyspace before discarding them, however we need to respect their `interval` parameter in some way. One approach could be to ignore/not requeue peers whose interval is more than a few seconds (could be calculated by `max_rt_nodes_size / max_rps`). This would have the disadvantage of discarding some good entries, but as we are crawling the dht these nodes would eventually show up again.

Another approach could be to actually track these interval spaces with some form of expiring list/map, where we would put these nodes into that map when they reply and once they expire we resend the requests to grab more infohashes, however this may cause issues with memory exhaustion as we saw with the current implementation.

The only downside I can think of, besides the slightly increased complexity, is that due to the protocol being UDP a good portion of our requests could be dropped in transit, and since we removed those nodes from our queue when we sent the `sample_infohashes` request, there could come a point where we are removing faster than we are acquiring new peers/nodes. This could be somewhat mitigated by keeping the `find_node` routine running, specially if it could react to how full our queue is.

The upside of course, is that we would be scanning each individual node as much as possible, possibly exhausting their share of infohashes, and would also be respecting the rate limit `interval` parameter as specified by BEP51. By also "moving on" as we query the nodes in the dht (instead of mostly re-requesting from nodes in our `rt.nodes` list every time indexing runs), we would be getting better infohash diversity and overall better quality/less duplicates.

**Comment by tgragnato** [comment]
> How often is this sampling done by magnetico?

The interval between consecutive `find_node` / `sample_infohashes` request trains is controlled by a ticker and can be adjusted using the `indexer-interval` flag. The current default is **1 second**.

> Could we be discarding entries by zeroing this list before that indexing request was ran?

Currently, entries are removed from the list during the indexing operations. Once the bootstrap process is complete, we stop using `find_node` queries and start sending only `sample_infohashes` queries to the peers. When peers are returned to the indexer, they are also removed from the routing table.

This is precisely why an accumulation of peers in the routing table indicates an excessive rate of traversal between DHT nodes. It might be useful to introduce a mechanism to dynamically increase or decrease the interval between indexing operations. This would enable magnetico to automatically adapt to the network capacity of each peer.

---

I’m splitting this issue into the following enhancement requests: https://github.com/tgragnato/magnetico/issues/479 - https://github.com/tgragnato/magnetico/issues/481
