### ISSUE TITLE
Optimizing the DHT crawling with a dynamic queue for infohash collection while adhering to BEP51 limits

### ISSUE THREAD

**Issue by tgragnato** [tgragnato/magnetico#479]
### Feature Request

Splitting off from https://github.com/tgragnato/magnetico/issues/476 - by @Fabricio20

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Based off of my interpretation of [BEP51](https://www.bittorrent.org/beps/bep_0051.html), for every single node, we can call `sample_infohashes` multiple times to obtain their entire hash table, respecting each peer's rate limits of course (which we are not doing at the moment it seems?), this means that for _some_ nodes in the dht we could be losing a lot of possible hashes by discarding them from this list.

If you are up to some relatively small design changes, I think a better approach would be to remove this list entirely, or at least replace it with a queue:

- Our crawler starts by sending out `find_node` requests to our bootstrap nodes, this creates a big list of nodes for us and can continually run in the background. *Note 1 below
- For every node that replies to our `find_node`, we put them in a queue `rt.nodes`.
- Another routine can pull/remove from this queue and send a `sample_infohashes` to this entry. *Note 2 below
- If a `sample_infohashes` response arrives which has `num` > `len(samples)` we can requeue the same node. *Note 3 below
- According to BEP51, this rpc call also returns the same output that `find_nodes` would, under the `nodes`/`nodes6` keys, so we can just add those to our `rt.nodes` queue as well.
- This should allow us to transverse the entire dht network as fast as we can send out requests.

There are a few interesting challenges with this approach of course:

Note 1: Some time after bootstrapping, as more and more peers reply to our `sample_infohashes` requests we may no longer need to run `find_node` queries, as the rate of replies should be enough to keep our queue reasonably full. We could stop this routine entirely or dynamically rate limit / slow it down based off of how full `rt.nodes` is (`len(rt.nodes) < maxNeighbors`).

Note 2: The queue is mainly here to allow us to rate limit how fast we are sending out infohash requests (`max_rps` would be used to limit how fast we are pulling from this queue), but could be removed entirely and just changed to simply sending data off of as soon as the responses arrive to other queries such as `find_node` or `sample_infohashes`. I'd be concerned with UDP exhaustion/dropped packets without the queue however.

Note 3: Readding these nodes is a good approach to ensure we exhaust their infohash keyspace before discarding them, however we need to respect their `interval` parameter in some way. One approach could be to ignore/not requeue peers whose interval is more than a few seconds (could be calculated by `max_rt_nodes_size / max_rps`). This would have the disadvantage of discarding some good entries, but as we are crawling the dht these nodes would eventually show up again.

Another approach could be to actually track these interval spaces with some form of expiring list/map, where we would put these nodes into that map when they reply and once they expire we resend the requests to grab more infohashes, however this may cause issues with memory exhaustion as we saw with the current implementation.

The only downside I can think of, besides the slightly increased complexity, is that due to the protocol being UDP a good portion of our requests could be dropped in transit, and since we removed those nodes from our queue when we sent the `sample_infohashes` request, there could come a point where we are removing faster than we are acquiring new peers/nodes. This could be somewhat mitigated by keeping the `find_node` routine running, specially if it could react to how full our queue is.

The upside of course, is that we would be scanning each individual node as much as possible, possibly exhausting their share of infohashes, and would also be respecting the rate limit `interval` parameter as specified by BEP51. By also "moving on" as we query the nodes in the dht (instead of mostly re-requesting from nodes in our `rt.nodes` list every time indexing runs), we would be getting better infohash diversity and overall better quality/less duplicates.

**Comment by tgragnato** [comment]
> Our crawler starts by sending out find_node requests to our bootstrap nodes, this creates a big list of nodes for us and can continually run in the background

This is the current behavior, but I do not want to DDoS the bootstrap nodes, so it’s not continuous: it only happens when the routing table is empty and needs to be bootstrapped again.

> If a sample_infohashes response arrives which has num > len(samples) we can requeue the same node
> Reading these nodes is a good approach to ensure we exhaust their infohash keyspace before discarding them, however we need to respect their interval parameter in some way. One approach could be to ignore/not requeue peers whose interval is more than a few seconds (could be calculated by max_rt_nodes_size / max_rps)

https://github.com/tgragnato/magnetico/blob/e3230a501b7568a21b978aacb1f0f7e6e50e9e97/dht/mainline/indexingService.go#L189

> According to BEP51, this rpc call also returns the same output that find_nodes would, under the nodes/nodes6 keys, so we can just add those to our rt.nodes queue as well.

https://github.com/tgragnato/magnetico/blob/e3230a501b7568a21b978aacb1f0f7e6e50e9e97/dht/mainline/indexingService.go#L192

I think that the internal data structures do not have the `nodes6` key. This needs to be checked and reviewed.

**Comment by tgragnato** [comment]
> I'd be concerned with UDP exhaustion/dropped packets without the queue however.

It's really a bad idea to crawl without any rate limiting. I am testing a patch that relaxes the rate limiting in certain cases. This creates a **_dual-tier system for sending DHT messages_**: one tier is rate-limited, while the other is prioritized.

In particular, my benchmarks show a 150+% increase in the number of torrents found with this tiering setup (compared to the baseline, by lowering max-rps to maintain a comparable overall number of packets).

Once `sample_infohash` queries return infohashes, retrieving peers and metadata is done with the highest possible priority and speed. **_This addresses the issue of UDP exhaustion while still focusing on obtaining results._**

**Comment by Fabricio20** [comment]
Hey @tgragnato Looks like some of the changes applied here completely broke the dht crawler. Running the current [HEAD](https://github.com/tgragnato/magnetico/commit/b148f1d73c563fa7b7e8ac3c3f30ca38b15add51) version yields about 1 torrent every 30s+ if that:

![image](https://github.com/user-attachments/assets/61b93308-15b6-4b62-ac34-73d8a334cb4f)

I did some dissecting and up until https://github.com/tgragnato/magnetico/commit/de6001b6fdaaa46f6dab8476813c7439bb3c59a6 the crawler is working fine and has an increase in performance as well:

![image](https://github.com/user-attachments/assets/9628242e-5485-41cd-81fa-c2468a238df9)

However by https://github.com/tgragnato/magnetico/commit/db977b7dcfb056e7f20604283f7a2a4b3c4ff381 the performance has severely degraded, and I believe max_rps change in https://github.com/tgragnato/magnetico/commit/79821e86fd98734c52aa1f210cc30a621554d514 is what ended up killing what peformance it had left.

My guess is responding to the dht requests from other peers is overloading the network on our end or similar, or perhaps throttle is taking into consideration those replies as well (though by this commit the default was still 0 so I dont think throttle is being applied here).

Logs now generated by magnetico in case they are helpful, they were pretty consistent between all tests.
```
Sep 01 15:03:25 dht magnetico[27841]: 2024/09/01 15:03:25
Sep 01 15:03:25 dht magnetico[27841]:  ---
Sep 01 15:03:25 dht magnetico[27841]: dht: 2815 errors occurred while writing a message to the UDP socket
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the peer connection was obfuscated with mse 51% of the time
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the extension set [0 0 0 0 0 16 0 1] was encountered 621 times
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the extension set [0 0 0 0 0 16 0 5] was encountered 389 times
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the extension set [0 0 0 0 0 24 0 5] was encountered 185 times
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the extension set [128 0 0 0 0 19 0 5] was encountered 42 times
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the extension set [0 0 0 0 0 16 0 4] was encountered 3 times
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the extension set [0 0 0 0 0 16 0 21] was encountered 2 times
Sep 01 15:03:25 dht magnetico[27841]: metainfo: the extension set [0 0 0 0 0 0 0 0] was encountered 1 times
Sep 01 15:03:25 dht magnetico[27841]:  ---
```

All these tests are were ran using `--indexer-max-neighbors=10000`.

**Comment by tgragnato** [comment]
**Wow, 2815 drops per min.** I bet your network is completely crushed!

The difference clearly lies in the ability to handle the packet rate of the entire protocol. Would you mind sharing more about your setup? Like the maximum number of file descriptors assigned to the process and the packet rate your network can handle.

![Screenshot 2024-09-01 alle 17 16 58](https://github.com/user-attachments/assets/8c7a9326-e838-402a-a943-149efb73d15a)
![Screenshot 2024-09-01 alle 17 18 01](https://github.com/user-attachments/assets/b263e7ee-0078-4880-954b-4a5a67d33fe0)
![Screenshot 2024-09-01 alle 17 31 50](https://github.com/user-attachments/assets/281c1231-d332-4492-aba5-70ddfbef89ce)

**Comment by tgragnato** [comment]
Hey @Fabricio20, I must have committed one too many goroutines compared to my build.
A race condition like that definitely has a negative impact on the number of results obtained.

However, that amount of UDP drops isn't healthy either.
I'll start looking into the possibilities for https://github.com/tgragnato/magnetico/issues/481 and for IPv6 support as soon as possible.

**Comment by Fabricio20** [comment]
No problem, I'm still investigating the status on the server at the moment, I did run one test manually removing that extra goroutine and it made no difference on my end!

I had max file descriptions at the default of 1024, increased to `524288` and now magnetico only complains about 12 errors at the very start (I think they might be Ipv6 too? since this host doesnt do ipv6 and it used to complain about some ipv6 ips before).

However I did install netdata to do some analysis and I'm having about ~8k UDP InError/s as well as ~7k UDP RcvbuffError/s (pre replies patch). So before going any further it might be good to track this down, I see you peak at 300 errors/s so it shouldn't be that bad for me. Though on the other hand I'm doing ~27kpps outgoing ~22kpps incoming which is a lot more than what you are pushing!

Network speed wise it's a "special" server, should have a 10Gb link to the router which has a massive 100Gb+ link to the outside world but due to some factors outside of my control it may be limited by the underlying infrastructure handling the VM. I'm whipping out another server in the meantime to compare performance under a different network setup as well.

Current Limits:
```
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             31627                31627                processes 
Max open files            524288               524288               files     
Max locked memory         8388608              8388608              bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       31627                31627                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us 
```

Let me know if you have any recommendations for what to look out for, parameters, limits and similar.

**Comment by tgragnato** [comment]
> magnetico only complains about 12 errors at the very start (I think they might be Ipv6 too?

The marshaller, unmarshaller, bootstrap, socket, and the leecher are IPv6-ready. The data structures and the logic inside `dht` still needs to be updated to handle the `want` and `nodes6` keys. So for now, you can safely ignore those errors; it won’t make any difference.

> should have a 10Gb link to the router

Those metrics are from my test bench, with only 20Mbps of uplink… Unless the network fabric is really poorly designed, I expect that a 10Gbps connection on enterprise hardware should be able to crawl with at least 2 to 3 orders of magnitude more.

To achieve that result, I tuned the [kernel settings](https://github.com/tgragnato/pure/blob/f511becfaeb72a089c8df456eee53163cbbde3ce/roles/base/tasks/network.yml#L48) to my use cases and used a [custom systemd unit](https://github.com/tgragnato/pure/blob/f511becfaeb72a089c8df456eee53163cbbde3ce/roles/services/templates/magnetico.service.j2#L2), but nothing more… You can do the same by adjusting the various parameters to fit your environment.

A unique aspect of magnetico is the use of a single UDP socket… Heavy-users have to configure at least the maximum number of connections, the UDP buffers and the queue management algorithm.
