### ISSUE TITLE
the magnet links displayed on the web interface are incorrect

### ISSUE THREAD

**Issue by lazyoop** [tgragnato/magnetico#523]
### Bug Report

| Q                   | A      |
| ------------------- | ------ |
| BC Break            | none |
| Version             | latest |

#### Summary
the magnet links displayed on the web interface are incorrect.

#### Current behavior
A normal magnet link should have a length of 40 characters, but the web interface shows a much longer length, which is clearly incorrect.

#### How to reproduce
1. I ran Magnetico, and the magnet links in the database are correct with a length of 40.
2. We can set a breakpoint at web/torrents.go:190 (the magnet link is correct at this point).
3. Open the web interface and perform a search by entering something arbitrary in the search box, like "test".
4. When we reach the breakpoint, we can see that the magnet link length is indeed 40, which is correct. Then, we continue running the program.
![true-find](https://github.com/user-attachments/assets/29825e8a-f2a2-4279-8e4d-11884db547f3)

5. The web interface starts to display the search results, but the magnet links become incorrect and are no longer 40 characters long.
![err-magnet-len](https://github.com/user-attachments/assets/60054e8f-1e57-4b00-85a5-537a9aa37518)

#### My guess
My guess is that the error might be caused here.
![code-err](https://github.com/user-attachments/assets/b321ec26-09d7-4572-aee8-c9c85fbf395a)

**Comment by lazyoop** [comment]
Or that there is a problem with the front-end display

**Comment by tgragnato** [comment]
If the length is correct at line 190, I think it’s more likely a front-end issue, perhaps an incompatibility with the browser you’re using. I haven’t been able to reproduce the issue on my end. What browser are you using?

**Comment by lazyoop** [comment]
chrome  131.0.6778.86

**Comment by lazyoop** [comment]
I guess I should make sure the problem is with the encoding. 
Prepare a magnet link for testing, such as: "83ec009d5dc7fc15d845fbfdb14d8fd156dc138a", then we find a character encoding/decoding website, use hexadecimal and UTF-8 to encode and get "38336 563303039643564633766633135643834356662666462313464386664313536646331333861", this is exactly what the web shows!

**Comment by tgragnato** [comment]
Sure: https://gchq.github.io/CyberChef/#recipe=To_Hex('Space',0)&input=ODNlYzAwOWQ1ZGM3ZmMxNWQ4NDVmYmZkYjE0ZDhmZDE1NmRjMTM4YQ&oeol=CRLF

But there’s a special marshaler for this reason. By any chance, have you changed it?
It's here: https://github.com/tgragnato/magnetico/blob/e130092009f6a9dc6672aa4431960ffb7eb75553/persistence/interface.go#L80 https://github.com/tgragnato/magnetico/blob/e130092009f6a9dc6672aa4431960ffb7eb75553/persistence/interface.go#L94

**Comment by lazyoop** [comment]
This part I haven't changed.

**Comment by tgragnato** [comment]
I can't reproduce this from the current master or any other release.
Does this problem occur when using the code of your fork or mine?

**Comment by lazyoop** [comment]
Sorry, this issue was caused by some changes I made to the code.    
I modified the persistence procedure, and during this process, there was a problem. The correct persistence of infohash should start with '0x', but mine does not, which caused the issue.
