### ISSUE TITLE
TODO: validateSampleInfohashesResponseMessage

### ISSUE THREAD

**Issue by capricornusx** [tgragnato/magnetico#6]
What do you mean by checking nodes?

https://github.com/tgragnato/magnetico/blob/2bbeebce172738a64a1cca25ce0d71dfa7a75d5d/dht/mainline/protocol.go#L450-L456

**Comment by tgragnato** [comment]
In this context `nodes` refers to the `Nodes field of a DHT response` (https://github.com/tgragnato/magnetico/blob/2f09c6ed2f2452ac3b21c73cc787f1c5b36e867d/dht/mainline/codec.go#L70C11-L70C11).

These functions are intended to validate the whole of a DHT response, but the current implementation only checks specific critical fields. The three TODO notes (one for each validation function) indicate the fields for which it would be crucial to complete the checks.
